/****************************************************************************
 * @file    header.inc
 * @date    2024-07-13 
 * @author  MonoKelvin
 * @email   15007083506@qq.com
 * @github  https://github.com/MonoKelvin
 * @brief
 *
 * This source file is part of Aproch.
 * Copyright (C) 2020 by MonoKelvin. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *****************************************************************************/
#pragma once

#include "AAbstractColorPicker.h"
#include "AAvatar.h"
#include "ACaptionBar.h"
#include "AColorPickerIndicator.h"
#include "AColorSliderControl.h"
#include "AFlowLayout.h"
#include "ANavigationBar.h"
#include "APromptWidget.h"
#include "AToolBar.h"
#include "AVerticalLabel.h"
#include "AWheelColorPicker.h"
#include "AWheelColorPickerWidget.h"
#include "AWidgetFactory.h"
#include "AWindow.h"
#include "ASplitterHandle.h"
#include "AFontIcon.h"
#include "AStaticTrackBar.h"
#include "AButton.h"
#include "AIconButton.h"
#include "AMenu.h"
#include "AComboBox.h"

#include "TextEditor/AFontSizeComboBox.h"
#include "TextEditor/AFontComboBox.h"
#include "TextEditor/ATextEditor.h"

#include "NavigationView/ANavigationPageView.h"
#include "NavigationView/ANavigationView.h"
#include "NavigationView/ANavigationMenuItem.h"

#include "Style/AWinUIStyle.h"
#include "Style/ATheme.h"
#include "Style/AWinUIStyleHelper.h"

#include "Animation/ADropDownAnimation.h"