// This file is autogenerated by CMake. Do not edit.
#include "stdafx.h"
#include <QtQml/qqmlextensionplugin.h>

//extern void qml_register_types_AWinUI();
//Q_GHS_KEEP_REFERENCE(qml_register_types_AWinUI);
//
//class AWinUIPlugin : public QQmlEngineExtensionPlugin
//{
//    Q_OBJECT;
//    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)
//public:
//    AWinUIPlugin(QObject* parent = nullptr) : QQmlEngineExtensionPlugin(parent)
//    {
//        volatile auto registration = &qml_register_types_AWinUI;
//        Q_UNUSED(registration)
//    }
//};
//
//
//#include "AWinUIPlugin.moc"